{% set name = "datasets" %}
{% set version = "2.19.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eccb82fb3bb5ee26ccc6d7a15b7f1f834e2cc4e59b7cff7733a003552bad51ef

build:
  noarch: python
  number: 0
  entry_points:
    - datasets-cli=datasets.commands.datasets_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.0
  run:
    - python >=3.8.0
    - filelock
    - numpy >=1.17
    - pyarrow >=12.0.0
    - pyarrow-hotfix
    - dill >=0.3.0,<0.3.9
    - pandas
    - requests >=2.32.1
    - tqdm >=4.62.1
    - python-xxhash
    - multiprocess
    - fsspec >=2023.1.0,<=2024.3.1
    - aiohttp
    - huggingface_hub >=0.21.2
    - packaging
    - pyyaml >=5.1

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.features
    - datasets.filesystems
    - datasets.formatting
    - datasets.io
    - datasets.packaged_modules
    - datasets.tasks
    - datasets.utils
  commands:
    - pip check
    - datasets-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  description: |
    Datasets is a lightweight library providing one-line dataloaders for many
    public datasets and one liners to download and pre-process any of the number
    of datasets major public datasets provided on the HuggingFace Datasets Hub.
    Datasets are ready to use in a dataloader for training/evaluating a ML model
    (Numpy/Pandas/PyTorch/TensorFlow/JAX). Datasets also provide an API for
    simple, fast, and reproducible data pre-processing for the above public
    datasets as well as your own local datasets in CSV/JSON/text.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
    - mxr-conda
